// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action_email: dynamic(() => import("./CallToActionEmail")),
  footer_list_block: dynamic(() => import("./FooterListBlock")),
  section_block_home: dynamic(() => import("./SectionBlockHome")),
  section_provided_services_home: dynamic(
    () => import("./SectionProvidedServicesHome"),
  ),
  section_two_block_home: dynamic(() => import("./SectionTwoBlockHome")),
  tabs_section: dynamic(() => import("./TabsSection")),
};
