import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/layout/header'
import Main from '@/layout/main'
import Footer from '@/layout/footer'
import header_image from '../image/header-back.jpg';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  return (
    <>
      <Head>
        <title>A5 Solution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0 maximum-scale=1.0, user-scalable=0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header isCoverImageVisiable={true} image_url={header_image.src} header_text='WELCOME TO A5 SOLUTION!' paragraph_text='BEST DYNAMICS AGENCY'/>
      <Main />
    </>
  )
}
export async function getStaticProps() {
  return {
    props: {}, // will be passed to the page component as props
  }
}

