import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/layout/header'
import Main from '@/layout/main'
import Footer from '@/layout/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>A5 Solution</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0 maximum-scale=1.0, user-scalable=0" />
        <link rel="icon" href="/favicon.ico" />
        <script async defer src="https://static.cdn.prismic.io/prismic.js?new=true&repo=next-a5"></script>
      </Head>
      <Header />
      <Main />
      <Footer />
    </>
  )
}
export async function getStaticProps() {
  return {
    props: {}, // will be passed to the page component as props
  }
}

